-- ============================================================================
-- KOVA catalog - 2026-27 kit FRONT VIEWS only (FootyLogos)
-- Generated by scripts/build-frentes-sql.mjs from
-- supabase/equipaciones-2026-27-frentes.json - DO NOT edit by hand.
-- 190 products - 539 front views - 58 teams skipped (no usable front view).
-- Each block sets images to the front view of every kit variant the team has,
-- replacing the previous full-gallery array (22-42 angles per kit).
-- Skipped teams keep their current imagery: see
-- supabase/equipaciones-2026-27-sin-frente.md
-- Idempotent: re-running writes the same values.
-- Rollback: supabase/equipaciones-2026-27-frentes-rollback.json
--   That snapshot holds the 279 equipaciones/2026-27 products as they were
--   immediately before this SQL ran, so it restores the previous galleries.
--   supabase/equipaciones-2026-27-backup.json is the older pre-FootyLogos Wix
--   snapshot and is NOT the rollback for this change.
-- ============================================================================
begin;

-- Real Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/real-madrid-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0099f14d-0945-4c89-9f8d-fa5a81ad504c';

-- Celta de Vigo | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/celta-vigo-2026-27/home-cover.webp","https://www.footylogos.com/kits/celta-vigo-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-celta-vigo-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '01018249-ca7d-4b32-86af-4a59b010029d';

-- RCD Espanyol | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/rcd-espanyol-barcelona-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rcd-espanyol-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rcd-espanyol-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '017cd38a-558d-4cee-879e-b774571d543d';

-- Sporting CP | 3 variants (home, away, anniversary)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-anniversary-kit-footylogos.jpg"]'::jsonb
  where p.id = '04270483-0036-4140-b610-ac06f712d323';

-- Sevilla FC | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-sevilla-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-sevilla-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-sevilla-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '05fc4705-8cab-4627-9bf6-4c08b93551ca';

-- Real Betis | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/real-betis-balompie-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-betis-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-betis-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '07839e04-8baf-4335-8dff-ff54e47c4ab4';

-- Elche CF | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-elche-cf-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-elche-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-elche-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '08d399e3-e802-475c-a59e-4b74c345dd19';

-- Athletic Club | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/athletic-club-bilbao-2026-27/home-cover.webp","https://www.footylogos.com/kits/athletic-club-bilbao-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-athletic-club-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0967c371-6439-4cdb-8f3d-5eb24938047e';

-- Ajax | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/ajax-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/eredivisie/batch-01/cover-ajax-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/ajax-2026-27/third-cover.webp"]'::jsonb
  where p.id = '0a383803-6962-4690-a430-7723f9c34ae0';

-- Arsenal | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/arsenal-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-arsenal-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-arsenal-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0ae62f62-9a2d-4bd9-8caf-86137b7e9a5b';

-- FC Koln | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/1-fc-koln-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-1-fc-koln-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-1-fc-koln-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0ae77950-f34a-47db-bb4d-397533e01c2b';

-- Leeds United | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-leeds-united-2026-27-home-kit-footylogos.jpg","https://www.footylogos.com/kits/leeds-united-2026-27/away-cover.webp","https://www.footylogos.com/kits/leeds-united-2026-27/third-cover.webp"]'::jsonb
  where p.id = '0cec400c-77ae-44f4-a73a-3c9da13d2c4c';

-- Internacional | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sc-internacional-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sc-internacional-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sc-internacional-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0d445266-d4ba-4f59-afe9-898643cea671';

-- Vasco da Gama | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-vasco-da-gama-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-vasco-da-gama-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '0d9ffb31-0631-4a3e-8a65-fe5779790f48';

-- Racing Santander | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-racing-de-santander-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-racing-de-santander-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '0efd30fc-06b0-4c49-bb32-54c8f5c0a374';

-- Eintracht Frankfurt | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/eintracht-frankfurt-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-eintracht-frankfurt-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-eintracht-frankfurt-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '0f25708d-0feb-4e2b-8f18-77828ca3a1a5';

-- Wrexham | 2 variants (away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-05/cover-wrexham-afc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/wrexham-afc-2026-27/third-cover.webp"]'::jsonb
  where p.id = '11ab9eb1-74e3-4bf5-a6be-cf429c8e09b9';

-- Real Sociedad | 3 variants (home, europa-league-away, europa-league-third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-real-sociedad-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-real-sociedad-2026-27-europa-league-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-real-sociedad-2026-27-europa-league-third-kit-footylogos.webp"]'::jsonb
  where p.id = '15372f13-ed1e-42cb-b9a0-a037204afb07';

-- Coventry City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/coventry-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-coventry-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/coventry-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = '169ed25c-db9e-4ba7-82a0-2eb5fad41818';

-- Santos | 3 variants (home, away, fourth)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-fourth-kit-footylogos.jpg"]'::jsonb
  where p.id = '18a79f76-f1e3-41ba-80e5-aebe4e89788b';

-- Valencia CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/valencia-cf-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-valencia-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-valencia-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '1ac54936-493a-4fb1-9ead-31869188d65c';

-- Corinthians | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '1ad5b00a-c2ff-47b3-9000-55a1c6542bb3';

-- Sheffield United | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-03/cover-sheffield-united-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-03/cover-sheffield-united-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-03/cover-sheffield-united-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '1b84eb5d-73fe-4d08-9145-9e85d55cef4d';

-- Como | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-02/cover-como-1907-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-02/cover-como-1907-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '1d06447d-b512-4d64-92f9-c34c25b41f6f';

-- Middlesbrough | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-02/cover-middlesbrough-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-02/cover-middlesbrough-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-02/cover-middlesbrough-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '1d93acc1-b9ad-4483-9999-b9cd2d17c9c1';

-- SC Freiburg | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/sc-freiburg-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-sc-freiburg-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/sc-freiburg-2026-27/third-cover.webp"]'::jsonb
  where p.id = '1e0cf603-17b2-404a-8abe-e77b8b367e17';

-- Chivas Guadalajara | 1 variant (home)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-cd-guadalajara-2026-27-home-kit-footylogos.jpg"]'::jsonb
  where p.id = '1e6bb418-e30c-4851-9e83-f86b7096eb89';

-- Bayer Leverkusen | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-bayer-leverkusen-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-bayer-leverkusen-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-bayer-leverkusen-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '1e989871-0d69-4376-993f-0a3f315aac38';

-- Bologna | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/bologna-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-02/cover-bologna-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '1f181402-91b3-4886-bdcc-58b9cbcbe4ce';

-- Bahia | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-bahia-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-bahia-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '1fdf52de-ddf9-4bbf-8a5e-a12feb11bb02';

-- Tigres UANL | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-tigres-uanl-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-tigres-uanl-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '216054fe-65f0-4488-8ad3-27ae52bd2923';

-- SL Benfica | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-third-kit-footylogos.webp"]'::jsonb
  where p.id = '2308b7eb-2667-4fd3-a87a-ff2dca93d8a4';

-- Hull City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/hull-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-hull-city-afc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/hull-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = '24fed334-b6e8-47f2-8cab-6d5b502d94a0';

-- RB Leipzig | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/rb-leipzig-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-rb-leipzig-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/rb-leipzig-2026-27/third-cover.webp"]'::jsonb
  where p.id = '25448a7f-bcda-4ead-a253-095e281505d9';

-- Sao Paulo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-sao-paulo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sao-paulo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sao-paulo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '2620c065-d86e-4bb0-8f89-4e1f98865d18';

-- Newcastle United | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '285b4054-0593-49f8-aad6-7a99fcaecbf1';

-- Nottingham Forest | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-nottingham-forest-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-nottingham-forest-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/nottingham-forest-2026-27/third-cover.webp"]'::jsonb
  where p.id = '2889e5a9-84fb-40ab-8619-d91de1d640b1';

-- Sunderland | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-sunderland-afc-2026-27-home-kit-footylogos.jpg","https://www.footylogos.com/kits/sunderland-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-sunderland-afc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '2a8bf773-3201-46aa-b32a-10291e236633';

-- Deportivo Alaves | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/deportivo-alaves-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-deportivo-alaves-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-deportivo-alaves-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '2acd9c27-0156-4462-a4d4-4a8da1d660de';

-- Fluminense | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '2b379569-a4fe-4186-be14-8c08ca3b97a1';

-- Inter Miami CF | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/inter-miami-2026/home-cover.webp","https://www.footylogos.com/kits/inter-miami-2026/away-cover.webp"]'::jsonb
  where p.id = '2f683de4-1f3d-4f31-80a2-3b2c8488de48';

-- Chapecoense | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-chapecoense-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-chapecoense-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '2fbd3dc3-b64b-4036-b9ae-78675fda34d2';

-- Rayo Vallecano | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '2fca61db-6372-4430-bab4-1aec80361ba9';

-- VfB Stuttgart | 5 variants (home, away, third, champions-league-away, champions-league-home)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-third-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-home-kit-footylogos.jpg"]'::jsonb
  where p.id = '3072e785-f267-4342-89d4-e1ff7cdd9cb3';

-- Monterrey | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-monterrey-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-monterrey-2026-27-away-kit-footylogos.avif"]'::jsonb
  where p.id = '30afc747-5e68-4651-9811-5228afd8efc1';

-- Atletico de Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/atletico-madrid-2026-27/home-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/away-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/third-cover.webp"]'::jsonb
  where p.id = '30e2d643-9c32-4954-b088-c08c04e43864';

-- PSV Eindhoven | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/eredivisie/batch-02/cover-psv-eindhoven-2026-27-home-kit-footylogos.jpg","https://www.footylogos.com/kits/psv-eindhoven-2026-27/away-cover.webp","https://www.footylogos.com/kits/psv-eindhoven-2026-27/third-cover.webp"]'::jsonb
  where p.id = '31e759a3-264b-4d38-880e-1b4da0d1a6fc';

-- Bahia | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-bahia-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-bahia-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '3296353d-9f14-476e-8705-c9d3a6eb646f';

-- Manchester City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/manchester-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/manchester-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = '3493a527-0ede-4485-925e-101abdcf9b34';

-- Real Betis | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/real-betis-balompie-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-betis-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-betis-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '360924ae-83df-488f-9a27-4517c959d69a';

-- Cruz Azul | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-cruz-azul-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-cruz-azul-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '3ae5615b-dce4-4198-a41b-ab9e0e58b377';

-- Villarreal CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/villarreal-cf-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-villarreal-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-villarreal-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '3c3d33d1-5e33-4310-abb1-60d5dd031042';

-- Chelsea | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/chelsea-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-chelsea-fc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/chelsea-2026-27/third-cover.webp"]'::jsonb
  where p.id = '3d6b7df1-31c4-4891-a632-ecdb18b685aa';

-- Feyenoord | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/feyenoord-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/eredivisie/batch-01/cover-feyenoord-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/feyenoord-2026-27/third-cover.webp"]'::jsonb
  where p.id = '3f2649db-a7f9-4397-985e-9eb8fad0801d';

-- LOSC Lille | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/ligue-1/batch-02/cover-losc-lille-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-02/cover-losc-lille-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/losc-lille-2026-27/third-cover.webp"]'::jsonb
  where p.id = '43913760-0db6-4303-9d35-e178facbf8f7';

-- AC Milan | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/ac-milan-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-ac-milan-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-ac-milan-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '44974078-af53-47f6-ad9f-85bbd06bd8f1';

-- Chivas Guadalajara | 1 variant (home)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-cd-guadalajara-2026-27-home-kit-footylogos.jpg"]'::jsonb
  where p.id = '4555ce0d-d551-4ab7-8a49-7d1a4c2e9137';

-- Getafe CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/getafe-cf-2026-27/home-cover.webp","https://www.footylogos.com/kits/getafe-cf-2026-27/away-cover.webp","https://www.footylogos.com/kits/getafe-cf-2026-27/third-cover.webp"]'::jsonb
  where p.id = '4670aac8-e35f-4e03-b51c-70ac2d886c0f';

-- SL Benfica | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-01/cover-sl-benfica-2026-27-third-kit-footylogos.webp"]'::jsonb
  where p.id = '46ad1d91-674b-4592-bffc-277902d5634d';

-- AS Monaco | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/as-monaco-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-01/cover-as-monaco-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-01/cover-as-monaco-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '475ce08c-0fc0-4f70-b9cd-0c4cccebb213';

-- VfB Stuttgart | 5 variants (home, away, third, champions-league-away, champions-league-home)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-third-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-home-kit-footylogos.jpg"]'::jsonb
  where p.id = '4775695b-ecb1-4e3b-98d0-781b8a527ad1';

-- Malaga | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-malaga-cf-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-malaga-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-malaga-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '47af375f-cd03-4cac-b467-4379b7abc96a';

-- Botafogo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-botafogo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-botafogo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-botafogo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '47ff149f-47fd-4fa5-8e15-4a910c01cde7';

-- Sporting CP | 3 variants (home, away, anniversary)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-03/cover-sporting-cp-2026-27-anniversary-kit-footylogos.jpg"]'::jsonb
  where p.id = '4841c303-e523-43f2-a454-f1b88804f2ff';

-- Atlante | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-atlante-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-atlante-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '49966589-5cd2-48ff-aab3-efdac753b31c';

-- Club America | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-club-america-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-club-america-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '4bd97a6d-2397-4220-a221-dbaa546361a4';

-- West Bromwich Albion | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-04/cover-west-bromwich-albion-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-04/cover-west-bromwich-albion-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/west-bromwich-albion-2026-27/third-cover.webp"]'::jsonb
  where p.id = '4e004dab-bb36-43fd-a015-a22e6c911df2';

-- Manchester City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/manchester-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/manchester-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = '50995352-0bab-460e-891a-13c381a7894c';

-- Preston North End | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/preston-north-end-2026-27/home-cover.webp","https://www.footylogos.com/kits/preston-north-end-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-02/cover-preston-north-end-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '52c61146-7456-4946-8bfe-7407bfab8d5b';

-- RC Lens | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/rc-lens-2026-27/home-cover.webp","https://www.footylogos.com/kits/rc-lens-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-rc-lens-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '539b1188-5ea6-40ca-9cd3-01bab63b88e3';

-- Tottenham Hotspur | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/tottenham-hotspur-2026-27/home-cover.webp","https://www.footylogos.com/kits/tottenham-hotspur-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-tottenham-hotspur-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '56e15a71-573c-42de-a1de-66fc482c1d71';

-- Flamengo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '58a63a1e-3d61-4bdf-a7a0-110786bde6ae';

-- Schalke 04 | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-schalke-04-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-schalke-04-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-schalke-04-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '5a31c318-78b8-4295-9ae7-24ebf5035039';

-- Brighton | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '5a47ef76-f64e-4663-8c36-ee0edfaceb6a';

-- Blackburn Rovers | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '5aa7259b-05e8-45fe-981f-4ca7f24a492c';

-- Toulouse | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-toulouse-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-04/cover-toulouse-fc-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '5c426498-6b88-40e6-8d68-f2ab485e28e4';

-- Coritiba | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-coritiba-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-coritiba-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-coritiba-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '5cdce63d-f2f9-4626-8433-950af759f030';

-- FC Barcelona | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/fc-barcelona-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-fc-barcelona-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-fc-barcelona-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '5e718b08-ead2-4c62-8f32-fbb7afcc422b';

-- Levante UD | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '620c3d14-997a-48d9-89b5-e7c7e96c47b1';

-- Hoffenheim | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/tsg-hoffenheim-2026-27/home-cover.webp","https://www.footylogos.com/kits/tsg-hoffenheim-2026-27/away-cover.webp","https://www.footylogos.com/kits/tsg-hoffenheim-2026-27/third-cover.webp"]'::jsonb
  where p.id = '6213bb67-2a1b-423e-bb51-f852a062f912';

-- AS Roma | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-as-roma-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-as-roma-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/as-roma-2026-27/third-cover.webp"]'::jsonb
  where p.id = '627fafd6-b2eb-421f-a4e8-b793f0ff9521';

-- Olympique de Marsella | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/olympique-de-marseille-om-2026-27/home-cover.webp","https://www.footylogos.com/kits/olympique-de-marseille-om-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-02/cover-olympique-de-marseille-om-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '66498bb0-d556-4a81-a2c3-2243d6e51c10';

-- Napoli | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-napoli-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-04/cover-napoli-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-04/cover-napoli-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '66ea0a5e-160d-4c5a-90bd-19aa232eb377';

-- Birmingham City | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-birmingham-city-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-birmingham-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/birmingham-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = '67d28f83-8874-4631-9914-cdc20b434a36';

-- PSV Eindhoven | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/eredivisie/batch-02/cover-psv-eindhoven-2026-27-home-kit-footylogos.jpg","https://www.footylogos.com/kits/psv-eindhoven-2026-27/away-cover.webp","https://www.footylogos.com/kits/psv-eindhoven-2026-27/third-cover.webp"]'::jsonb
  where p.id = '695335f6-f8c9-460a-9292-add39db23941';

-- FC Porto | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '6bda97c0-ca56-4f92-9c84-7c49538d886f';

-- SC Freiburg | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/sc-freiburg-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-sc-freiburg-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/sc-freiburg-2026-27/third-cover.webp"]'::jsonb
  where p.id = '6be1e5e1-0e16-4d3f-855d-cc9ea8bf61e4';

-- Celtic | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-third-kit-footylogos.webp"]'::jsonb
  where p.id = '7089f986-0866-45dc-bcca-cd603c395d7d';

-- RCD Espanyol | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/rcd-espanyol-barcelona-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rcd-espanyol-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rcd-espanyol-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '714b98a7-058b-434c-a772-40c1b4ab5561';

-- Nottingham Forest | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-nottingham-forest-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-nottingham-forest-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/nottingham-forest-2026-27/third-cover.webp"]'::jsonb
  where p.id = '714c2dff-c12d-4644-aa5a-1ba99f6a35c7';

-- Napoli | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-napoli-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-04/cover-napoli-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-04/cover-napoli-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '71596adb-1a74-40da-b1d5-eaa1ddc3c2bd';

-- Fiorentina | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-fiorentina-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-fiorentina-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '7436304d-ca2d-4ace-884b-f7e4130ce49e';

-- AS Monaco | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/as-monaco-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-01/cover-as-monaco-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-01/cover-as-monaco-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '75e40155-be75-4504-9f0a-c4b49c54815b';

-- FC Koln | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/1-fc-koln-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-1-fc-koln-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-01/cover-1-fc-koln-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '777288b9-961a-4590-9a08-991942721cf1';

-- Malaga | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-malaga-cf-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-malaga-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-malaga-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '77dade92-9273-4f25-a8be-9064a336dc6d';

-- Arsenal | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/arsenal-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-arsenal-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-arsenal-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '787a1017-e7d1-4230-b1e1-19fd2f18a135';

-- Eintracht Frankfurt | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/eintracht-frankfurt-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-eintracht-frankfurt-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-eintracht-frankfurt-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '7f17ecb8-71e3-44e0-920c-c9541e35dc2d';

-- AS Roma | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-as-roma-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-as-roma-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/as-roma-2026-27/third-cover.webp"]'::jsonb
  where p.id = '7fb787af-84f9-4ae2-9962-4f627a6e38aa';

-- Vasco da Gama | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-vasco-da-gama-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-vasco-da-gama-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '806ffe9c-5b89-4445-81a4-57162bf6e73a';

-- Fulham | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '8140769c-70fc-4ccb-afca-8afe979a9a76';

-- Racing Santander | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-racing-de-santander-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-racing-de-santander-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '83fea0aa-54ac-480a-bb16-e14bf2ebd591';

-- Athletic Club | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/athletic-club-bilbao-2026-27/home-cover.webp","https://www.footylogos.com/kits/athletic-club-bilbao-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-athletic-club-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '866b2947-2fec-45ae-86be-85f52bebd180';

-- Borussia Dortmund | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/borussia-dortmund-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-dortmund-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-dortmund-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '8763fe7a-ad88-4e6e-81ad-a7154ee0c371';

-- Chelsea | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/chelsea-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-chelsea-fc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/chelsea-2026-27/third-cover.webp"]'::jsonb
  where p.id = '878ce3af-69ee-4798-a347-ae25ede9c2bc';

-- Juventus | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/juventus-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-juventus-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-juventus-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '883569b1-9aa1-4426-9972-650a8528355e';

-- Everton | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/everton-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-everton-fc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/everton-2026-27/third-cover.webp"]'::jsonb
  where p.id = '88975b7c-dadc-4dfc-8254-4ce22929b889';

-- Real Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/real-madrid-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '8a1e9c95-214a-4a70-88df-ca99edab76cf';

-- Cardiff City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/cardiff-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-cardiff-city-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-cardiff-city-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '8c6f9886-e869-447e-9241-156eda495b9f';

-- Santos Laguna | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-santos-laguna-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-santos-laguna-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '8cdd4a52-c435-447a-b18e-37338773d353';

-- VfB Stuttgart | 5 variants (home, away, third, champions-league-away, champions-league-home)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-vfb-stuttgart-2026-27-third-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-04/cover-vfb-stuttgart-2026-27-champions-league-home-kit-footylogos.jpg"]'::jsonb
  where p.id = '8e148517-6550-4edf-9262-04b9f1a55db1';

-- Hamburgo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-hamburger-sv-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-hamburger-sv-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/hamburger-sv-2026-27/third-cover.webp"]'::jsonb
  where p.id = '8e32c6e1-93d2-499a-91f7-e243baa89b22';

-- Tigres UANL | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-tigres-uanl-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-tigres-uanl-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '8f9a6d3f-bf5e-4116-b1c8-ad6a40a036ae';

-- Villarreal CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/villarreal-cf-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-villarreal-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-villarreal-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '94aad117-3714-4c27-b4bf-aabda222eb4f';

-- Getafe CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/getafe-cf-2026-27/home-cover.webp","https://www.footylogos.com/kits/getafe-cf-2026-27/away-cover.webp","https://www.footylogos.com/kits/getafe-cf-2026-27/third-cover.webp"]'::jsonb
  where p.id = '9736f468-2ac3-4572-9386-efc44e2c59da';

-- FK Bod?/Glimt | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-01/cover-fk-bodo-glimt-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-01/cover-fk-bodo-glimt-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '97425d47-3bae-4827-a242-0be99fdca9c5';

-- Inter Miami CF | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/inter-miami-2026/home-cover.webp","https://www.footylogos.com/kits/inter-miami-2026/away-cover.webp"]'::jsonb
  where p.id = '98a73594-3df6-4a74-8c36-f5a8b927487a';

-- Borussia Monchengladbach | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/borussia-monchengladbach-2026-27/home-cover.webp","https://www.footylogos.com/kits/borussia-monchengladbach-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-monchengladbach-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '98b0d04c-50d0-4827-a36c-3ae52190d6bb';

-- Corinthians | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-corinthians-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '9972582f-ed58-482b-af26-845c92d02001';

-- SC Freiburg | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/sc-freiburg-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/bundesliga-batch-03-rebuilt/cover-sc-freiburg-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/sc-freiburg-2026-27/third-cover.webp"]'::jsonb
  where p.id = '99e1c455-c1ed-41db-ab89-0eeb85e3268a';

-- Brentford | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '99edebfd-4dbc-4115-8d60-65ff2e138280';

-- Deportivo de La Coruna | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/deportivo-la-coruna-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-deportivo-de-a-coruna-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-deportivo-de-a-coruna-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '9b5de270-523a-4083-b53f-1a479f8fb5df';

-- Palmeiras | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-palmeiras-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-palmeiras-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = '9e20a667-574e-407b-b6c3-862fafc6fd19';

-- Real Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/real-madrid-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-real-madrid-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = '9f38fe3b-43f3-490e-846a-830a8c14d052';

-- Hull City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/hull-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-hull-city-afc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/hull-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'a0c1e4c0-cbe5-4b49-9095-8fba2dbae878';

-- Manchester United | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/manchester-united-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-united-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-united-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'a61cf2bc-e6d4-4b0d-8510-cf94cd79a8a7';

-- Gremio | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-gremio-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-gremio-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-gremio-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'a85190e0-e923-4e73-b457-5c11c5c63c30';

-- Fluminense | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-fluminense-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'a92afaca-4d0e-4513-87bc-67f3f83f3377';

-- Atlas | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-atlas-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-atlas-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'aa0f0c0d-b929-4b74-8505-c98f25ffe60f';

-- Everton | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/everton-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-everton-fc-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/everton-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'ab66f42d-be35-432e-8c6e-052c27fdf50b';

-- Werder Bremen | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-werder-bremen-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-werder-bremen-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/werder-bremen-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'abba0f92-b15f-48dd-a675-4dc7b7e3baa0';

-- Atletico de Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/atletico-madrid-2026-27/home-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/away-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'abc52fc6-cce0-4ea3-9c6e-b71eeb81c2f2';

-- Derby County | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/derby-county-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-derby-county-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/derby-county-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'abe428d1-31c2-4386-8c28-801ee3f078db';

-- Remo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-club-de-remo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-club-de-remo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-club-de-remo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'abe9c767-57d4-4180-8028-12ccfe476126';

-- Werder Bremen | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-werder-bremen-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-werder-bremen-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/werder-bremen-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'b0ef1ab9-9458-48f0-82c5-831893ac6a07';

-- Inter de Milan | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/inter-milan-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-inter-milan-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/inter-milan-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'b12a80da-7d36-4745-bc14-7b6446eb0a61';

-- Aston Villa | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/aston-villa-2026-27/home-cover.webp","https://www.footylogos.com/kits/aston-villa-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-aston-villa-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'b48194ac-b061-4dd5-858f-adb3f6ac7e80';

-- Brentford | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'b6d01f0b-e25e-430f-947a-2a7eb2beaf1d';

-- Cruzeiro | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-cruzeiro-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-02/cover-cruzeiro-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-cruzeiro-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'b8648fc9-a9a7-4dce-967f-30daf9826fa2';

-- Toluca | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-toluca-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-toluca-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'ba47e076-156f-4c72-8002-e4a09b03a739';

-- Pumas UNAM | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-pumas-unam-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-pumas-unam-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'bbf6459a-168e-40ff-aeeb-d5d7fed44e87';

-- Manchester City | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/manchester-city-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/manchester-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'bf28123e-09a7-4411-ae83-ac3e7ad04880';

-- Ipswich Town | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/ipswich-town-2026-27/home-cover.webp","https://www.footylogos.com/kits/ipswich-town-2026-27/away-cover.webp"]'::jsonb
  where p.id = 'c0405b0e-6bee-41f5-8160-cde5bdb1b268';

-- Rayo Vallecano | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-rayo-vallecano-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c0609581-e573-4bdc-b301-d85489275058';

-- Fulham | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-fulham-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c2808ae1-bb4c-4841-aa8b-dbdf44295af6';

-- Tottenham Hotspur | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/tottenham-hotspur-2026-27/home-cover.webp","https://www.footylogos.com/kits/tottenham-hotspur-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-tottenham-hotspur-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c2e1ff6f-f88f-42dc-b580-ffc7e9353200';

-- Levante UD | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-levante-ud-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c430441c-8a04-45c5-bbaf-b7d119537c7f';

-- New York City FC | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/new-york-city-fc-2026/home-cover.webp","https://www.footylogos.com/kits/new-york-city-fc-2026/away-cover.webp"]'::jsonb
  where p.id = 'c547ce83-183f-4516-9e0e-690fd4eb0dff';

-- FC Porto | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-fc-porto-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c7365506-d5d7-4327-ac07-2927f7e8808d';

-- Celtic | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-02/cover-celtic-2026-27-third-kit-footylogos.webp"]'::jsonb
  where p.id = 'c7600375-aef5-49f9-a97e-7e952611f3b8';

-- Athletico Paranaense | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-athletico-paranaense-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-athletico-paranaense-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-athletico-paranaense-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c8283d06-85a5-4923-923e-243d960bd00b';

-- Sevilla FC | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-03/cover-sevilla-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-sevilla-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-sevilla-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c84ad884-9896-4873-b0a2-fb9d1ca0ddf9';

-- RC Lens | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/rc-lens-2026-27/home-cover.webp","https://www.footylogos.com/kits/rc-lens-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-rc-lens-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'c89cd49b-fbcd-491f-ae9d-f37c4085cf47';

-- Valencia CF | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/valencia-cf-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-valencia-cf-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-04/cover-valencia-cf-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'caba4d86-24f0-4791-a272-d65060b1a115';

-- Pumas UNAM | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-pumas-unam-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-03/cover-pumas-unam-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'cc5a77b7-bbe9-4704-bff7-663a1c1e1982';

-- Borussia Dortmund | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/borussia-dortmund-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-dortmund-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-dortmund-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'cd419373-cc73-48fa-8657-5937de07a5e4';

-- Inter de Milan | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/inter-milan-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/uefa-champions-league/batch-02/cover-inter-milan-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/inter-milan-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'd1fc3fdf-bc80-4450-9702-46794f065785';

-- Atletico de Madrid | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/atletico-madrid-2026-27/home-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/away-cover.webp","https://www.footylogos.com/kits/atletico-madrid-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'd2b2aad5-2c0c-4de5-b670-46979d3e9fe5';

-- Olympiacos | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-olympiacos-2026-27-home-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-olympiacos-2026-27-away-kit-footylogos.webp","https://assets.footylogos.com/kits/2026-27/uefa-europa-league/batch-04/cover-olympiacos-2026-27-third-kit-footylogos.webp"]'::jsonb
  where p.id = 'd3876696-9880-47d2-b128-2c49552cc840';

-- Olympique de Lyon | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/olympique-lyonnais-2026-27/home-cover.webp","https://www.footylogos.com/kits/olympique-lyonnais-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-02/cover-olympique-lyonnais-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'd3b34cf3-aabf-4d4f-b0f3-8cb819d027f7';

-- Hamburgo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-hamburger-sv-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-hamburger-sv-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/hamburger-sv-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'd4a7efef-9950-4a3c-9609-1cd5aa5c9c31';

-- Palmeiras | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-palmeiras-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-palmeiras-2026-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'd5c2242f-0195-4b22-941d-780d2ee1e44e';

-- Juventus | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/juventus-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-juventus-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-juventus-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'd95ed641-cda1-489c-b73f-d2fd671a580b';

-- Birmingham City | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-birmingham-city-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-birmingham-city-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/birmingham-city-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'da7979f3-f292-4740-8e19-98fae9ac9366';

-- Atletico Mineiro | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'db73e75a-9d20-4e59-8dd4-53694b56eed4';

-- Stade Rennais | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/stade-rennais-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-stade-rennais-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-stade-rennais-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'dc49d128-9eec-4878-b942-d11637dee2c1';

-- Sao Paulo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-sao-paulo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sao-paulo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-05/cover-sao-paulo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'dedbd131-5de6-40ed-8c99-242fff94ecd8';

-- Bologna | 2 variants (home, away)
update products p set images = '["https://www.footylogos.com/kits/bologna-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-02/cover-bologna-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'df894657-d761-4cd2-a564-9490026f399b';

-- Estrasburgo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-rc-strasbourg-alsace-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-03/cover-rc-strasbourg-alsace-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/rc-strasbourg-alsace-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'e019f059-0e5a-4cdf-a630-2fb1371cd3a6';

-- AC Milan | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/ac-milan-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-ac-milan-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-ac-milan-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e068fd3b-5a05-4e81-8563-2265e785c2a7';

-- Tijuana | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-club-tijuana-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-02/cover-club-tijuana-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e2e3e655-c58d-4482-a844-83e1bd9c8eb9';

-- Santos | 3 variants (home, away, fourth)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-04/cover-santos-fc-2026-fourth-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e4d2422d-3719-4eac-8615-c792e7298a8c';

-- Atletico Mineiro | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-01/cover-atletico-mineiro-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e6afc774-53e3-462d-b5b9-e2353b7f4956';

-- Club America | 2 variants (home, away)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-club-america-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/liga-mx/batch-01/cover-club-america-2026-27-away-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e72caa7a-5f29-48c5-bb9a-cc592e741761';

-- Ajax | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/ajax-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/eredivisie/batch-01/cover-ajax-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/ajax-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'e730bb4f-8756-4bfc-97ca-256030b9e0c6';

-- FC Barcelona | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/fc-barcelona-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-fc-barcelona-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-02/cover-fc-barcelona-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e7a448da-bbf9-4ef2-af61-593ca92efc29';

-- Aston Villa | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/aston-villa-2026-27/home-cover.webp","https://www.footylogos.com/kits/aston-villa-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-aston-villa-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'e9387b00-7e5d-4ae7-8b8e-9ebfbab5be3c';

-- Parma | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-parma-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-parma-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/parma-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'e956f3bc-06ee-498f-a6ef-2cbb3ad8d716';

-- Borussia Monchengladbach | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/borussia-monchengladbach-2026-27/home-cover.webp","https://www.footylogos.com/kits/borussia-monchengladbach-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-02/cover-borussia-monchengladbach-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'ea9ff93e-6bf1-467e-b7c7-a46a137f6bd0';

-- Union Berlin | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/union-berlin-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-union-berlin-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/bundesliga/batch-04/cover-union-berlin-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'ebf5c258-283d-410b-8145-d59254c60607';

-- Flamengo | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026/brasileirao-serie-a/batch-03/cover-flamengo-2026-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'eed5283a-2074-436b-9883-47345309aeab';

-- Lazio | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-lazio-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-lazio-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-03/cover-lazio-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'ef61bbfc-776b-4401-8434-31a300ceb968';

-- Blackburn Rovers | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/efl-championship/batch-01/cover-blackburn-rovers-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'f0b7089e-79ba-419b-a2bf-961ae188abba';

-- Newcastle United | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-newcastle-united-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'f3d87f9a-1d21-4cc3-9a8f-3fa59315f1e5';

-- Olympique de Marsella | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/olympique-de-marseille-om-2026-27/home-cover.webp","https://www.footylogos.com/kits/olympique-de-marseille-om-2026-27/away-cover.webp","https://assets.footylogos.com/kits/2026-27/ligue-1/batch-02/cover-olympique-de-marseille-om-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'f75f001b-5d88-4362-9387-2b06d18a4a5b';

-- Manchester United | 3 variants (home, away, third)
update products p set images = '["https://www.footylogos.com/kits/manchester-united-2026-27/home-cover.webp","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-united-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-manchester-united-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'f9266bfd-82d4-4d09-90de-4229ed4133d7';

-- Brighton | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brighton-hove-albion-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'f935409a-bd39-46f4-9cac-1f588e56e12f';

-- CA Osasuna | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'fc206d96-c0d3-4194-b9e0-6f6b718a6531';

-- Brentford | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/premier-league/batch-04/cover-brentford-fc-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'fca80c06-070e-4c74-8dba-6c276d9b5841';

-- Atalanta | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-atalanta-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/serie-a/batch-01/cover-atalanta-2026-27-away-kit-footylogos.jpg","https://www.footylogos.com/kits/atalanta-2026-27/third-cover.webp"]'::jsonb
  where p.id = 'fd4d9da7-dadf-49e0-adeb-0c355e4ea039';

-- CA Osasuna | 3 variants (home, away, third)
update products p set images = '["https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-home-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-away-kit-footylogos.jpg","https://assets.footylogos.com/kits/2026-27/laliga/batch-01/cover-ca-osasuna-2026-27-third-kit-footylogos.jpg"]'::jsonb
  where p.id = 'fea29ddf-dad6-460d-a50f-606dfc4f87e1';

commit;
